// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLKQ5oiljVkhzJGdAL6bg225EPFOymEDk',
    appId: '1:1000550306677:web:975bd2406482f37868b93c',
    messagingSenderId: '1000550306677',
    projectId: 'sokivibes',
    authDomain: 'sokivibes.firebaseapp.com',
    storageBucket: 'sokivibes.firebasestorage.app',
    measurementId: 'G-1Y97HTYNB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKDg7sxsHV-xUT0qQOJTL0sd6P59Xn7Ic',
    appId: '1:1000550306677:android:9e989b2407b1207f68b93c',
    messagingSenderId: '1000550306677',
    projectId: 'sokivibes',
    storageBucket: 'sokivibes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVHio_Ut3yVwjI9apqKgrYwPkVguc86rs',
    appId: '1:1000550306677:ios:b106e31b3925c43c68b93c',
    messagingSenderId: '1000550306677',
    projectId: 'sokivibes',
    storageBucket: 'sokivibes.firebasestorage.app',
    iosBundleId: 'com.example.sokivibesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVHio_Ut3yVwjI9apqKgrYwPkVguc86rs',
    appId: '1:1000550306677:ios:b106e31b3925c43c68b93c',
    messagingSenderId: '1000550306677',
    projectId: 'sokivibes',
    storageBucket: 'sokivibes.firebasestorage.app',
    iosBundleId: 'com.example.sokivibesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLKQ5oiljVkhzJGdAL6bg225EPFOymEDk',
    appId: '1:1000550306677:web:29a8ae308575cff568b93c',
    messagingSenderId: '1000550306677',
    projectId: 'sokivibes',
    authDomain: 'sokivibes.firebaseapp.com',
    storageBucket: 'sokivibes.firebasestorage.app',
    measurementId: 'G-PQQJFQ5Q9D',
  );
}
